Repository apache/rocketmq-externals, pull requests merged in 2019-08, with the labels that each got.

#362 [ISSUE #361] Change the name of the parameter workerSourceTasks to workerTasks
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java
Labels: enhancement

#360 [ISSUE #359] Fix file connect sink task stop bug
  rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSinkTask.java
Labels: bug

#358 [ISSUE #357] Supplementary readme documentation
  rocketmq-connect/README.md
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/RuntimeConfigDefine.java
Labels: enhancement

#355 [ISSUE #351] rmq client setInstanceName on sourceTask
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceConnector.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceTask.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/common/Utils.java
Labels: enhancement

#366 [ISSUE 368]Polish rocketmq replicator implementation
  rocketmq-connect/rocketmq-connect-runtime/src/main/resources/package.xml
  rocketmq-replicator/README.md
  rocketmq-replicator/package.xml
  rocketmq-replicator/pom.xml
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java
Labels: enhancement

#367 [ISSUE #369]Polish rocketmq connect pom file and config
  rocketmq-connect/README.md
  rocketmq-connect/pom.xml
  rocketmq-connect/rocketmq-connect-runtime/pom.xml
  rocketmq-connect/rocketmq-connect-runtime/run_worker.sh
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectConfig.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/OffsetManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/resources/connect.conf
  rocketmq-connect/rocketmq-connect-sample/pom.xml
Labels: enhancement

#364 [ISSUE #363] File connector configures a separate log file
  rocketmq-connect/rocketmq-connect-runtime/src/main/resources/logback.xml
  rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSinkTask.java
  rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/FileSourceTask.java
  rocketmq-connect/rocketmq-connect-sample/src/main/java/org/apache/rocketmq/connect/file/LoggerName.java
Labels: enhancement

#348 [ISSUE #345]merge rmq client
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/datasync/BrokerBasedLog.java
Labels: bug

#384 [ISSUE #385]Add acl feature support for rocketmq-flink
  rocketmq-flink/pom.xml
  rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQConfig.java
  rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSink.java
  rocketmq-flink/src/main/java/org/apache/rocketmq/flink/RocketMQSource.java
Labels: enhancement

#387 [ISSUE #375]Refactoring cluster discovery module, removed the message exchange dependency
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectStartup.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectConfig.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/RuntimeConfigDefine.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSourceTask.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementService.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/OffsetManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceService.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/strategy/AllocateConnAndTaskStrategy.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/strategy/DefaultAllocateConnAndTaskStrategy.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/ConnectUtil.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/datasync/BrokerBasedLog.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/resources/connect.conf
  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/config/ConnectConfigTest.java
  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTest.java
  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/rest/RestHandlerTest.java
  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/ClusterManagementServiceImplTest.java
  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImplTest.java
  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/PositionManagementServiceImplTest.java
  rocketmq-connect/rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/strategy/DefaultAllocateConnAndTaskStrategyTest.java
Labels: enhancement

#390 [ISSUE #389] Runtime support load fat jar
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/PluginClassLoader.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/PluginUtils.java
Labels: new feature
