Repository apache/rocketmq-externals, pull requests merged in 2019-07, with the labels that each got.

#315 [ISSUE #293] Implement source connector of rocketmq-connect-kafka
  rocketmq-connect-kafka/pom.xml
  rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/Config.java
  rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceConnector.java
  rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceTask.java
  rocketmq-connect-kafka/src/main/resources/connect-kafka-source.properties
  rocketmq-connect-kafka/src/test/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceConnectorTest.java
  rocketmq-connect-kafka/src/test/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceTaskTest.java
Labels: new feature

#309 Define and Implement the RmqConnector and RmqSourceTask
  rocketmq-replicator/.gitignore
  rocketmq-replicator/pom.xml
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqConstants.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceConnector.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/RmqSourceTask.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/common/Utils.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/ConfigDefine.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/ConfigUtil.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/DataType.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/config/TaskConfig.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/schema/FieldName.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/DivideStrategyEnum.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/DivideTaskByQueue.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/DivideTaskByTopic.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/connector/strategy/TaskDivideStrategy.java
Labels: new feature

#316 Write rocketmq-connect-runtime Chinese readme.md
  rocketmq-connect-runtime/README.md
Labels: enhancement

#324 [ISSUE #323] Add connectorContext support
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectController.java
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerConnector.java
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementService.java
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImpl.java
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/DefaultConnectorContext.java
  rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java
  rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerConnectorTest.java
  rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerTest.java
  rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestConnector.java
  rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/connectorwrapper/testimpl/TestTask.java
  rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/rest/RestHandlerTest.java
  rocketmq-connect-runtime/src/test/java/org/apache/rocketmq/connect/runtime/service/ConfigManagementServiceImplTest.java
Labels: enhancement, new feature

#313 [ISSUE #312] Implement rocketmq connect RabbitMQ
  rocketmq-connect-jms/README-CN.md
  rocketmq-connect-jms/README.md
  rocketmq-connect-jms/pom.xml
  rocketmq-connect-jms/rocketmq-connect-jms.iml
  rocketmq-connect-jms/src/main/java/org/apache/rocketmq/connect/jms/Config.java
  rocketmq-connect-jms/src/main/java/org/apache/rocketmq/connect/jms/connector/BaseJmsSourceConnector.java
  rocketmq-connect-jms/src/main/java/org/apache/rocketmq/connect/jms/connector/BaseJmsSourceTask.java
  rocketmq-connect-jms/src/main/java/org/apache/rocketmq/connect/jms/pattern/PatternProcessor.java
  rocketmq-connect-jms/src/test/java/org/apache/rocketmq/connect/jms/ReplicatorTest.java
  rocketmq-connect-jms/src/test/java/org/apache/rocketmq/connect/jms/connector/ActivemqSourceTaskTest.java
  rocketmq-connect-jms/src/test/java/org/apache/rocketmq/connect/jms/connector/BaseJmsSourceConnectorTest.java
  rocketmq-connect-rabbitmq/README.md
  rocketmq-connect-rabbitmq/pom.xml
  rocketmq-connect-rabbitmq/src/main/java/org/apache/rocketmq/connect/rabbitmq/ErrorCode.java
  rocketmq-connect-rabbitmq/src/main/java/org/apache/rocketmq/connect/rabbitmq/RabbitmqConfig.java
  rocketmq-connect-rabbitmq/src/main/java/org/apache/rocketmq/connect/rabbitmq/connector/RabbitmqSourceConnector.java
  rocketmq-connect-rabbitmq/src/main/java/org/apache/rocketmq/connect/rabbitmq/connector/RabbitmqSourceTask.java
  rocketmq-connect-rabbitmq/src/main/java/org/apache/rocketmq/connect/rabbitmq/pattern/RabbitMQPatternProcessor.java
  rocketmq-connect-rabbitmq/src/test/java/org/apache/rocketmq/connect/jms/RabbitmqConfigTest.java
  rocketmq-connect-rabbitmq/src/test/java/org/apache/rocketmq/connect/rabbitmq/connector/RabbitmqSourceConnectorTest.java
  rocketmq-connect-rabbitmq/src/test/java/org/apache/rocketmq/connect/rabbitmq/connector/RabbitmqSourceTaskTest.java
  rocketmq-connect-rabbitmq/src/test/java/org/apache/rocketmq/connect/rabbitmq/pattern/RabbitMQPatternProcessorTest.java
Labels: new feature

#342 [ISSUE #341] Add wakeup before kafka consumer close to wakeup consumer poll
  rocketmq-connect-kafka/src/main/java/org/apache/rocketmq/connect/kafka/connector/KafkaSourceTask.java
Labels: enhancement

#347 [ISSUE #344] Update the fastjson version of runtime to 1.2.58
  rocketmq-connect/rocketmq-connect-runtime/pom.xml
Labels: enhancement
