Repository apache/rocketmq-externals, pull requests merged in 2019-09, with the labels that each got.

#370 [ISSUE #371]Develop Jdbc Source Connector
  rocketmq-connect-jdbc/README.md
  rocketmq-connect-jdbc/pom.xml
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/Config.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceConnector.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceTask.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/Database.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/Schema.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/Table.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/BigIntColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/ColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/DateTimeColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/DefaultColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/EnumColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/IntColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/SetColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/StringColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/TimeColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/schema/column/YearColumnParser.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/source/JdbcUtils.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/source/Querier.java
  rocketmq-connect-jdbc/src/main/java/org/apache/rocketmq/connect/jdbc/source/TimestampIncrementingQuerier.java
  rocketmq-connect-jdbc/src/test/java/org/apache/rocketmq/connect/jdbc/connector/JdbcSourceConnectorTest.java
Labels: new feature

#416 [ISSUE #396]Automatically create target topic
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigDefine.java
Labels: enhancement, new feature

#391 [ISSUE #377] Isolation load connector
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/Plugin.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/utils/PluginClassLoader.java
Labels: new feature

#414 [ISSUE #399]Topic rename.
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/common/Utils.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/ConfigDefine.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskTopicInfo.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByTopic.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/TaskDivideStrategy.java
  rocketmq-replicator/src/test/java/org/apache/rocketmq/replicator/RmqSourceReplicatorTest.java
Labels: enhancement, new feature

#421 [ISSUE #397] Add DivideTaskByQueue
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/config/TaskTopicInfo.java
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/strategy/DivideTaskByQueue.java
Labels: new feature

#422 [ISSUE #386] Fix sourceTaskTopicList is null
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
Labels: enhancement

#424 [ISSUE #398]Increase topic change awareness monitoring
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceReplicator.java
Labels: new feature
