Repository apache/rocketmq-externals, pull requests merged in 2021-09, with the labels that each got.

#795 [ISSUE #796] add task woker thread name
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/Worker.java
Labels: enhancement

#797 [ISSUE #798] fields will not be built in SinkDataEntry
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
Labels: bug

#800 [ISSUE #801]Rocketmq connector sink for hudi
  rocketmq-connect-hudi/README.md
  rocketmq-connect-hudi/pom.xml
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/config/CloneUtils.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/config/ConfigUtil.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/config/HudiConnectConfig.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/config/SinkConnectConfig.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/config/Utils.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/connector/HudiSinkConnector.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/connector/HudiSinkTask.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/sink/Updater.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/strategy/ITaskDivideStrategy.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/strategy/TaskDivideByQueueStrategy.java
  rocketmq-connect-hudi/src/main/java/org/apache/rocketmq/connect/hudi/strategy/TaskDivideStrategyFactory.java
  rocketmq-connect-hudi/style/rmq_checkstyle.xml
  rocketmq-connect/pom.xml
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/ConnectStartup.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/config/ConnectConfig.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/connectorwrapper/WorkerSinkTask.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/rest/RestHandler.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/java/org/apache/rocketmq/connect/runtime/service/RebalanceImpl.java
  rocketmq-connect/rocketmq-connect-runtime/src/main/resources/connect.conf
  rocketmq-connect/rocketmq-connect-runtime/src/main/resources/log4j.properties
  rocketmq-connect/rocketmq-connect-runtime/src/main/resources/user.avsc
Labels: new feature

#700 [ISSUE #699] The source task starts to check the position
  rocketmq-replicator/src/main/java/org/apache/rocketmq/replicator/RmqSourceTask.java
Labels: enhancement
